[pytest]
addopts = --alluredir=reports/allure-results
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    ui: UI tests
    api: API tests
    positive: marks tests as positive "happy path" scenarios
    negative: marks tests as negative/sad path scenarios